[build]
builder = "nixpacks"
buildCommand = "rm -f package-lock.json && npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
